### ISSUE TITLE
Migrate to Go modules

### ISSUE THREAD

**Issue by invidian** [flatcar-linux/locksmith#3]
Instead of using Glide, Go modules should be used for dependency management.

**Comment by vbatts** [comment]
```
# github.com/flatcar-linux/locksmith/locksmithctl
locksmithctl/locksmithctl.go:233:35: cannot use kapi (type client.KeysAPI) as type lock.KeysAPI in argument to lock.NewEtcdLockClient:
        client.KeysAPI does not implement lock.KeysAPI (wrong type for Create method)
                have Create("github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/context".Context, string, string) (*client.Response, error)
                want Create("golang.org/x/net/context".Context, string, string) (*client.Response, error)
make: *** [Makefile:28: bin/locksmithctl] Error 2
```
This rule about the "longest import path is preferred" is tricky. Since with `go mod` every time you even `go build` something it will do some checks on the remote.

**Comment by dmlambea** [comment]
I've managed to get a compilable version in my `go-module` branch, at https://github.com/dmlambea/locksmith/tree/go-module

Remarkable things I've done there:
- Created the module descriptor using github.com/flatcar-linux/locksmith
- Fixed the import paths of 'coreos/locksmith'
- Added a 'replace' directive in the module descriptor, to overcome the error shown in `go mod tidy`, about importing bbolt from go.etcd.io/bbolt and from github.com/coreos/bbolt
- Fixed the type of 'object' field in Client struct, which seemed to be wrong.

All tests passes.

If the changes look Ok for you, I can open a PR.

**Comment by vbatts** [comment]
@dmlambea nice. Be sure to rebase on the main branch. Some of the import paths were touched in #2. Also some of the changes like the 'object' field may best be a separate PR. But please feel free to open PRs non-the-less.

**Comment by dmlambea** [comment]
@vbatts, thank you!. I've opened the first PR with the go module changes in #4. If you like it, I'll open the fix for 'object' field based on the new tree.

**Comment by pothos** [comment]
Thanks @dmlambea!
